environment:
  matrix:
    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      JAVA_HOME: C:\Program Files\Java\jdk21
    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-21-openjdk-amd64
    - job_name: macOS
      APPVEYOR_BUILD_WORKER_IMAGE: macos-sonoma
      JAVA_HOME: /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home

matrix:
  fast_finish: true

for:

  # ======================================
  #      Windows
  # ======================================

  -
    matrix:
      only:
        - job_name: Windows

    init:
      - echo "Init for Windows"

    build_script:
      - gradlew.bat packageReleaseUberJarForCurrentOS

    test: off

  # ======================================
  #      Linux
  # ======================================

  -
    matrix:
      only:
        - job_name: Linux

    init:
      - echo "Init for Linux"

    build_script:
      - ./gradlew packageReleaseUberJarForCurrentOS

    test: off

  # ======================================
  #      macOS
  # ======================================

  -
    matrix:
      only:
        - job_name: macOS

    init:
      - export PATH=$JAVA_HOME/bin:$PATH

    build_script:
      - echo "sdk.dir=$HOME/android-sdk" > local.properties
      - mkdir -p $HOME/android-sdk
      - ./gradlew packageReleaseUberJarForCurrentOS

    test: off

artifacts:
  - path: app/build/compose/jars/*.jar
