version: 1.0.{build}

# Build matrix for Windows, macOS, Linux
matrix:
  os:
    - Windows
    - macOS
    - Ubuntu

# Environment
environment:
  JAVA_HOME_21_x64:
    matrix:
      - WINDOWS: C:\Program Files\Azul\zulu-21
      - MACOS: /Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home
      - UBUNTU: /usr/lib/jvm/zulu-21-amd64

# Install dependencies
install:
  - ps: if ($env:APPVEYOR_OS -eq "Windows") { choco install gradle -y }
  - bash: if [ "$APPVEYOR_OS" = "Linux" ] || [ "$APPVEYOR_OS" = "macOS" ]; then brew install gradle || sudo apt-get install -y gradle; fi

# Set JDK
before_build:
  - set JAVA_HOME=%JAVA_HOME_21_x64%
  - set PATH=%JAVA_HOME%\bin;%PATH%

# Build command
build: 
  - gradle packageReleaseUberJarForCurrentOS

# Artifacts
artifacts:
  - path: build/libs/*.jar
