environment:
  matrix:
    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

    - job_name: macOS
      APPVEYOR_BUILD_WORKER_IMAGE: macos-sonoma

matrix:
  fast_finish: true

for:

  # ======================================
  #      Windows
  # ======================================

  -
    matrix:
      only:
        - job_name: Windows

    init:
      - echo "Init for Windows"

    build_script:
      - gradlew.bat packageReleaseUberJarForCurrentOS

    test: off

  # ======================================
  #      Linux
  # ======================================

  -
    matrix:
      only:
        - job_name: Linux

    init:
      - echo "Init for Linux"

    build_script:
      - ./gradlew packageReleaseUberJarForCurrentOS

    test: off

  # ======================================
  #      macOS
  # ======================================

  -
    matrix:
      only:
        - job_name: macOS

    init:
      - echo "Init for macOS"

    build_script:
      -./gradlew packageReleaseUberJarForCurrentOS

    test: off

artifacts:
  - path: app/build/compose/jars/*.jar
