comments:
  CommentOverPrivateProperty:
    active: true
  EndOfSentenceFormat:
    active: true
  OutdatedDocumentation:
    active: true

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
  MatchingDeclarationName:
    multiplatformTargets:
      - android
      - desktop

style:
  MagicNumber:
    active: false
  ReturnCount:
    excludeGuardClauses: true